rainforest/config/routes.rb
Rails.application.routes.draw do

  root :to => 'products#index'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

end

rainforest/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rainforest/app/models/product.rb
class Product < ApplicationRecord

  validates :name, :description, :price, presence: true

  validates_uniqueness_of :name

  validates :price, numericality: {
                                  only_integer: true,
                                  greater_than_or_equal_to: 0.0
                                  }

  has_many :reviews

  def price_in_dollars
    price_in_dollars = price.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

end

rainforest/app/models/review.rb
class Review < ApplicationRecord

  validates :review_text, presence: true

  belongs_to :product

end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new
    @product.name = params[:product][:name]
    @product.price = params[:product][:price]
    @product.description = params[:product][:description]

    if @product.save
      flash[:notice] = "You have successfully created a new product."
      redirect_to products_url
    else
      render "/products/new"
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.name = params[:product][:name]
    @product.price = params[:product][:price]
    @product.description = params[:product][:description]

    if @product.save
      flash[:notice] = "You have successfully updated your product."
      redirect_to products_url
    else
      redirect_to edit_products_url
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "You have successfully deleted your product."
    redirect_to products_url
  end



end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
  end

  def create
    @product = Product.find(params["product_id"])
    product = Product.find(params["product_id"])
    @review = Review.new
    @review.review_text = params[:review][:review_text]
    @review.product = product

    if @review.save
      flash[:notice] = "You have successfully created a new review."
      redirect_to product_url(product)
    else
      render '/products/show'
    end
  end

  def update
  @review = Review.find(params[:id])
  @product = @review.product
  @review.review_text = params[:review][:review_text]

  if @review.save
    redirect_to "/products/#{@product.id}"
  else
    render "/reviews/edit"
  end
  end

  def edit
    @review = Review.find(params[:id])
    flash[:notice] = "You have successfully edited your review."
    @product = @review.product
  end

  def destroy
    @review = Review.find(params[:id])
    @product = @review.product
    @review.destroy
    flash[:notice] = "You have successfully deleted your review."
    redirect_to "/products/#{@product.id}"
  end

end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest Shopping Center</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav>
        <ul>
          <li class='navbar'><%= link_to "Home", root_path, class: "navbar_text" %></li>
          <li class='navbar'><%=link_to "Add New Product", "/products/new", class: "navbar_text" %></li>
        </ul>
      </nav>

      <% if flash[:notice] %>
        <p class="notice"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
        <p class="alert"><%= flash[:alert] %></p>
      <% end %>

    <%= yield %>

    <footer>
      <ul>
        <li class='navbar'><%= link_to "Home", root_path, class: "footer_text" %></li>
        <li class='navbar'><%=link_to "Add New Product", "/products/new", class: "footer_text" %></li>
      </ul>
    </footer>

  </body>
</html>

rainforest/app/views/products/_product_form.html.erb
<%= link_to "Back to index", "/products" %>

<%= form_for product do |form_helper| %>

  <p>
    <%= form_helper.label :name %>:
    <%= form_helper.text_field :name %>
  </p>

  <p>
    <%= form_helper.label :price %>:
    <%= form_helper.number_field :price %>
  </p>

  <p>
    <%= form_helper.label :description %>:
    <%= form_helper.text_field :description %>
  </p>

  <p>
    <%= form_helper.submit "Submit" %>
  </p>

<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Edit Product</h1>


<%= render "product_form", product: @product %>

rainforest/app/views/products/index.html.erb
<div class="products_page_wrapper">
  <% @products.each do |product| %>
    <div class="product_wrapper">
      <ul>
        <li class='product_info'>
          <span class="product_name">
            <%= link_to "#{product.name}:", "/products/#{product.id}" %>
          </span>

          <span class="product_price">
            <%= product.price_in_dollars %>
          </span>
        </li>

        <li class='image_tab'>
          <%= link_to(image_tag("https://picsum.photos/200/200/?random"), "products/#{product.id}") %>
        </li>

        <li class='product_description'>
          <%= product.description %>
        </li>

      </ul>
    </div>
  <% end %>
</div>

rainforest/app/views/products/new.html.erb
<h1>Add a New Product</h1>

<%= render "product_form", product: @product %>

<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

rainforest/app/views/products/show.html.erb
<h1><%= "#{@product.name.capitalize}" %></h1>

<p><%= link_to "Back to index", "/products" %></p>

<img src="https://picsum.photos/200/200?random" alt="">
<p><%=@product.name%> : <%=@product.price_in_dollars %></p>

<p><%= link_to "Edit", "/products/#{@product.id}/edit" %> |
<%= link_to "Delete", product_path(@product), method: :delete, data: {confirm: "Are you definitely sure you want to delete this product? It's pretty awesome, and can never come back."} %></p>

<p>
  Reviews:<br>
  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <div class="review_text">
          <%= review.review_text %>
        </div>
        <div class="review_time">
          <%= review.created_at %>
        </div>
        <div class="review_edit">
          <%= link_to "Edit review", "/products/#{@product.id}/reviews/#{review.id}/edit" %>
        </div>
      </li>
    <% end %>
  </ul>
</p>

<%= form_for([@product, @review]) do |form_helper| %>
  <p>
    <%= form_helper.label :review_text %>:
    <%= form_helper.text_field :review_text %>
  </p>
 <p>
   <%= form_helper.submit 'submit' %>
 </p>

<% end %>

rainforest/app/views/reviews/edit.html.erb
<h1>Edit Reviews</h1>

<%= link_to "Back to index", "/products" %>

<h2><%= "#{@product.name.capitalize}" %></h2>

<%= form_for ([@product, @review]) do |form_helper| %>

  <p>
    <%= form_helper.label :review_text %>:
    <%= form_helper.text_field :review_text %>
  </p>

  <p>
    <%= link_to "Delete this review", product_review_path(@review), method: :delete, data: {confirm: "Are you definitely sure you want to delete this review? It's pretty awesome, and can never come back."} %>
  </p>

  <p>
    <%= form_helper.submit "Submit" %>
  </p>

<% end %>